#:schema taplo://taplo.toml

[formatting]
  # https://taplo.tamasfe.dev/configuration/formatter-options.html
  allowed_blank_lines = 1
  indent_entries = true
  indent_tables = true
  indent_string = "  "
  reorder_arrays = true
