#!/usr/bin/env bash

set -euo pipefail

export PYTHONPATH="$PWD"

printf "\nWhich script would you like to run? [#]\n\n"

scripts=("modem/restart.py")

select script in "${scripts[@]}"; do
  [[ -n "$script" ]] && uv run "$script" || echo "No script selected."
  break
done
