#!/usr/bin/env bash

set -euo pipefail

export DRY_RUN=${DRY_RUN:-false}
export PYTHONPATH="$PWD"

echo "Dry run mode: $DRY_RUN"

printf "\nWhich script would you like to run? [#]\n\n"

scripts=("modem/restart.py")

select script in "${scripts[@]}"; do
  [[ -n "$script" ]] && uv run "$script" || echo "No script selected."
  break
done
